// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyber/proto/parameter.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cyber_2fproto_2fparameter_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_cyber_2fproto_2fparameter_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cyber_2fproto_2fparameter_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cyber_2fproto_2fparameter_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cyber_2fproto_2fparameter_2eproto;
namespace apollo {
namespace cyber {
namespace proto {
class BoolResult;
class BoolResultDefaultTypeInternal;
extern BoolResultDefaultTypeInternal _BoolResult_default_instance_;
class NodeName;
class NodeNameDefaultTypeInternal;
extern NodeNameDefaultTypeInternal _NodeName_default_instance_;
class Param;
class ParamDefaultTypeInternal;
extern ParamDefaultTypeInternal _Param_default_instance_;
class ParamName;
class ParamNameDefaultTypeInternal;
extern ParamNameDefaultTypeInternal _ParamName_default_instance_;
class Params;
class ParamsDefaultTypeInternal;
extern ParamsDefaultTypeInternal _Params_default_instance_;
}  // namespace proto
}  // namespace cyber
}  // namespace apollo
PROTOBUF_NAMESPACE_OPEN
template<> ::apollo::cyber::proto::BoolResult* Arena::CreateMaybeMessage<::apollo::cyber::proto::BoolResult>(Arena*);
template<> ::apollo::cyber::proto::NodeName* Arena::CreateMaybeMessage<::apollo::cyber::proto::NodeName>(Arena*);
template<> ::apollo::cyber::proto::Param* Arena::CreateMaybeMessage<::apollo::cyber::proto::Param>(Arena*);
template<> ::apollo::cyber::proto::ParamName* Arena::CreateMaybeMessage<::apollo::cyber::proto::ParamName>(Arena*);
template<> ::apollo::cyber::proto::Params* Arena::CreateMaybeMessage<::apollo::cyber::proto::Params>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace apollo {
namespace cyber {
namespace proto {

enum ParamType : int {
  NOT_SET = 0,
  BOOL = 1,
  INT = 2,
  DOUBLE = 3,
  STRING = 4,
  PROTOBUF = 5
};
bool ParamType_IsValid(int value);
constexpr ParamType ParamType_MIN = NOT_SET;
constexpr ParamType ParamType_MAX = PROTOBUF;
constexpr int ParamType_ARRAYSIZE = ParamType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ParamType_descriptor();
template<typename T>
inline const std::string& ParamType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ParamType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ParamType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ParamType_descriptor(), enum_t_value);
}
inline bool ParamType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ParamType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ParamType>(
    ParamType_descriptor(), name, value);
}
// ===================================================================

class Param PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.Param) */ {
 public:
  inline Param() : Param(nullptr) {}
  virtual ~Param();

  Param(const Param& from);
  Param(Param&& from) noexcept
    : Param() {
    *this = ::std::move(from);
  }

  inline Param& operator=(const Param& from) {
    CopyFrom(from);
    return *this;
  }
  inline Param& operator=(Param&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Param& default_instance();

  enum OneofValueCase {
    kBoolValue = 4,
    kIntValue = 5,
    kDoubleValue = 6,
    kStringValue = 7,
    ONEOF_VALUE_NOT_SET = 0,
  };

  static inline const Param* internal_default_instance() {
    return reinterpret_cast<const Param*>(
               &_Param_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Param& a, Param& b) {
    a.Swap(&b);
  }
  inline void Swap(Param* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Param* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Param* New() const final {
    return CreateMaybeMessage<Param>(nullptr);
  }

  Param* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Param>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Param& from);
  void MergeFrom(const Param& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Param* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.cyber.proto.Param";
  }
  protected:
  explicit Param(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cyber_2fproto_2fparameter_2eproto);
    return ::descriptor_table_cyber_2fproto_2fparameter_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kTypeNameFieldNumber = 3,
    kProtoDescFieldNumber = 8,
    kTypeFieldNumber = 2,
    kBoolValueFieldNumber = 4,
    kIntValueFieldNumber = 5,
    kDoubleValueFieldNumber = 6,
    kStringValueFieldNumber = 7,
  };
  // optional string name = 1;
  bool has_name() const;
  private:
  bool _internal_has_name() const;
  public:
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // optional string type_name = 3;
  bool has_type_name() const;
  private:
  bool _internal_has_type_name() const;
  public:
  void clear_type_name();
  const std::string& type_name() const;
  void set_type_name(const std::string& value);
  void set_type_name(std::string&& value);
  void set_type_name(const char* value);
  void set_type_name(const char* value, size_t size);
  std::string* mutable_type_name();
  std::string* release_type_name();
  void set_allocated_type_name(std::string* type_name);
  private:
  const std::string& _internal_type_name() const;
  void _internal_set_type_name(const std::string& value);
  std::string* _internal_mutable_type_name();
  public:

  // optional bytes proto_desc = 8;
  bool has_proto_desc() const;
  private:
  bool _internal_has_proto_desc() const;
  public:
  void clear_proto_desc();
  const std::string& proto_desc() const;
  void set_proto_desc(const std::string& value);
  void set_proto_desc(std::string&& value);
  void set_proto_desc(const char* value);
  void set_proto_desc(const void* value, size_t size);
  std::string* mutable_proto_desc();
  std::string* release_proto_desc();
  void set_allocated_proto_desc(std::string* proto_desc);
  private:
  const std::string& _internal_proto_desc() const;
  void _internal_set_proto_desc(const std::string& value);
  std::string* _internal_mutable_proto_desc();
  public:

  // optional .apollo.cyber.proto.ParamType type = 2;
  bool has_type() const;
  private:
  bool _internal_has_type() const;
  public:
  void clear_type();
  ::apollo::cyber::proto::ParamType type() const;
  void set_type(::apollo::cyber::proto::ParamType value);
  private:
  ::apollo::cyber::proto::ParamType _internal_type() const;
  void _internal_set_type(::apollo::cyber::proto::ParamType value);
  public:

  // bool bool_value = 4;
  bool has_bool_value() const;
  private:
  bool _internal_has_bool_value() const;
  public:
  void clear_bool_value();
  bool bool_value() const;
  void set_bool_value(bool value);
  private:
  bool _internal_bool_value() const;
  void _internal_set_bool_value(bool value);
  public:

  // int64 int_value = 5;
  bool has_int_value() const;
  private:
  bool _internal_has_int_value() const;
  public:
  void clear_int_value();
  ::PROTOBUF_NAMESPACE_ID::int64 int_value() const;
  void set_int_value(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_int_value() const;
  void _internal_set_int_value(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // double double_value = 6;
  bool has_double_value() const;
  private:
  bool _internal_has_double_value() const;
  public:
  void clear_double_value();
  double double_value() const;
  void set_double_value(double value);
  private:
  double _internal_double_value() const;
  void _internal_set_double_value(double value);
  public:

  // string string_value = 7;
  bool has_string_value() const;
  private:
  bool _internal_has_string_value() const;
  public:
  void clear_string_value();
  const std::string& string_value() const;
  void set_string_value(const std::string& value);
  void set_string_value(std::string&& value);
  void set_string_value(const char* value);
  void set_string_value(const char* value, size_t size);
  std::string* mutable_string_value();
  std::string* release_string_value();
  void set_allocated_string_value(std::string* string_value);
  private:
  const std::string& _internal_string_value() const;
  void _internal_set_string_value(const std::string& value);
  std::string* _internal_mutable_string_value();
  public:

  void clear_oneof_value();
  OneofValueCase oneof_value_case() const;
  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.Param)
 private:
  class _Internal;
  void set_has_bool_value();
  void set_has_int_value();
  void set_has_double_value();
  void set_has_string_value();

  inline bool has_oneof_value() const;
  inline void clear_has_oneof_value();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr proto_desc_;
  int type_;
  union OneofValueUnion {
    OneofValueUnion() {}
    bool bool_value_;
    ::PROTOBUF_NAMESPACE_ID::int64 int_value_;
    double double_value_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr string_value_;
  } oneof_value_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_cyber_2fproto_2fparameter_2eproto;
};
// -------------------------------------------------------------------

class NodeName PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.NodeName) */ {
 public:
  inline NodeName() : NodeName(nullptr) {}
  virtual ~NodeName();

  NodeName(const NodeName& from);
  NodeName(NodeName&& from) noexcept
    : NodeName() {
    *this = ::std::move(from);
  }

  inline NodeName& operator=(const NodeName& from) {
    CopyFrom(from);
    return *this;
  }
  inline NodeName& operator=(NodeName&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const NodeName& default_instance();

  static inline const NodeName* internal_default_instance() {
    return reinterpret_cast<const NodeName*>(
               &_NodeName_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(NodeName& a, NodeName& b) {
    a.Swap(&b);
  }
  inline void Swap(NodeName* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NodeName* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NodeName* New() const final {
    return CreateMaybeMessage<NodeName>(nullptr);
  }

  NodeName* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NodeName>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const NodeName& from);
  void MergeFrom(const NodeName& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NodeName* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.cyber.proto.NodeName";
  }
  protected:
  explicit NodeName(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cyber_2fproto_2fparameter_2eproto);
    return ::descriptor_table_cyber_2fproto_2fparameter_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
  };
  // optional string value = 1;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  const std::string& value() const;
  void set_value(const std::string& value);
  void set_value(std::string&& value);
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  std::string* mutable_value();
  std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.NodeName)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
  friend struct ::TableStruct_cyber_2fproto_2fparameter_2eproto;
};
// -------------------------------------------------------------------

class ParamName PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.ParamName) */ {
 public:
  inline ParamName() : ParamName(nullptr) {}
  virtual ~ParamName();

  ParamName(const ParamName& from);
  ParamName(ParamName&& from) noexcept
    : ParamName() {
    *this = ::std::move(from);
  }

  inline ParamName& operator=(const ParamName& from) {
    CopyFrom(from);
    return *this;
  }
  inline ParamName& operator=(ParamName&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ParamName& default_instance();

  static inline const ParamName* internal_default_instance() {
    return reinterpret_cast<const ParamName*>(
               &_ParamName_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ParamName& a, ParamName& b) {
    a.Swap(&b);
  }
  inline void Swap(ParamName* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ParamName* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ParamName* New() const final {
    return CreateMaybeMessage<ParamName>(nullptr);
  }

  ParamName* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ParamName>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ParamName& from);
  void MergeFrom(const ParamName& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ParamName* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.cyber.proto.ParamName";
  }
  protected:
  explicit ParamName(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cyber_2fproto_2fparameter_2eproto);
    return ::descriptor_table_cyber_2fproto_2fparameter_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
  };
  // optional string value = 1;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  const std::string& value() const;
  void set_value(const std::string& value);
  void set_value(std::string&& value);
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  std::string* mutable_value();
  std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.ParamName)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
  friend struct ::TableStruct_cyber_2fproto_2fparameter_2eproto;
};
// -------------------------------------------------------------------

class BoolResult PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.BoolResult) */ {
 public:
  inline BoolResult() : BoolResult(nullptr) {}
  virtual ~BoolResult();

  BoolResult(const BoolResult& from);
  BoolResult(BoolResult&& from) noexcept
    : BoolResult() {
    *this = ::std::move(from);
  }

  inline BoolResult& operator=(const BoolResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline BoolResult& operator=(BoolResult&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BoolResult& default_instance();

  static inline const BoolResult* internal_default_instance() {
    return reinterpret_cast<const BoolResult*>(
               &_BoolResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(BoolResult& a, BoolResult& b) {
    a.Swap(&b);
  }
  inline void Swap(BoolResult* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BoolResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BoolResult* New() const final {
    return CreateMaybeMessage<BoolResult>(nullptr);
  }

  BoolResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BoolResult>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BoolResult& from);
  void MergeFrom(const BoolResult& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BoolResult* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.cyber.proto.BoolResult";
  }
  protected:
  explicit BoolResult(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cyber_2fproto_2fparameter_2eproto);
    return ::descriptor_table_cyber_2fproto_2fparameter_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
  };
  // optional bool value = 1;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  bool value() const;
  void set_value(bool value);
  private:
  bool _internal_value() const;
  void _internal_set_value(bool value);
  public:

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.BoolResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  bool value_;
  friend struct ::TableStruct_cyber_2fproto_2fparameter_2eproto;
};
// -------------------------------------------------------------------

class Params PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.Params) */ {
 public:
  inline Params() : Params(nullptr) {}
  virtual ~Params();

  Params(const Params& from);
  Params(Params&& from) noexcept
    : Params() {
    *this = ::std::move(from);
  }

  inline Params& operator=(const Params& from) {
    CopyFrom(from);
    return *this;
  }
  inline Params& operator=(Params&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Params& default_instance();

  static inline const Params* internal_default_instance() {
    return reinterpret_cast<const Params*>(
               &_Params_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Params& a, Params& b) {
    a.Swap(&b);
  }
  inline void Swap(Params* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Params* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Params* New() const final {
    return CreateMaybeMessage<Params>(nullptr);
  }

  Params* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Params>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Params& from);
  void MergeFrom(const Params& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Params* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.cyber.proto.Params";
  }
  protected:
  explicit Params(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cyber_2fproto_2fparameter_2eproto);
    return ::descriptor_table_cyber_2fproto_2fparameter_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kParamFieldNumber = 1,
  };
  // repeated .apollo.cyber.proto.Param param = 1;
  int param_size() const;
  private:
  int _internal_param_size() const;
  public:
  void clear_param();
  ::apollo::cyber::proto::Param* mutable_param(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::Param >*
      mutable_param();
  private:
  const ::apollo::cyber::proto::Param& _internal_param(int index) const;
  ::apollo::cyber::proto::Param* _internal_add_param();
  public:
  const ::apollo::cyber::proto::Param& param(int index) const;
  ::apollo::cyber::proto::Param* add_param();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::Param >&
      param() const;

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.Params)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::Param > param_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cyber_2fproto_2fparameter_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Param

// optional string name = 1;
inline bool Param::_internal_has_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Param::has_name() const {
  return _internal_has_name();
}
inline void Param::clear_name() {
  name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Param::name() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Param.name)
  return _internal_name();
}
inline void Param::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.name)
}
inline std::string* Param::mutable_name() {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.Param.name)
  return _internal_mutable_name();
}
inline const std::string& Param::_internal_name() const {
  return name_.Get();
}
inline void Param::_internal_set_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Param::set_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.Param.name)
}
inline void Param::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.Param.name)
}
inline void Param::set_name(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.Param.name)
}
inline std::string* Param::_internal_mutable_name() {
  _has_bits_[0] |= 0x00000001u;
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Param::release_name() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.Param.name)
  if (!_internal_has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Param::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.Param.name)
}

// optional .apollo.cyber.proto.ParamType type = 2;
inline bool Param::_internal_has_type() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Param::has_type() const {
  return _internal_has_type();
}
inline void Param::clear_type() {
  type_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::apollo::cyber::proto::ParamType Param::_internal_type() const {
  return static_cast< ::apollo::cyber::proto::ParamType >(type_);
}
inline ::apollo::cyber::proto::ParamType Param::type() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Param.type)
  return _internal_type();
}
inline void Param::_internal_set_type(::apollo::cyber::proto::ParamType value) {
  assert(::apollo::cyber::proto::ParamType_IsValid(value));
  _has_bits_[0] |= 0x00000008u;
  type_ = value;
}
inline void Param::set_type(::apollo::cyber::proto::ParamType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.type)
}

// optional string type_name = 3;
inline bool Param::_internal_has_type_name() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Param::has_type_name() const {
  return _internal_has_type_name();
}
inline void Param::clear_type_name() {
  type_name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Param::type_name() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Param.type_name)
  return _internal_type_name();
}
inline void Param::set_type_name(const std::string& value) {
  _internal_set_type_name(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.type_name)
}
inline std::string* Param::mutable_type_name() {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.Param.type_name)
  return _internal_mutable_type_name();
}
inline const std::string& Param::_internal_type_name() const {
  return type_name_.Get();
}
inline void Param::_internal_set_type_name(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  type_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Param::set_type_name(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  type_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.Param.type_name)
}
inline void Param::set_type_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  type_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.Param.type_name)
}
inline void Param::set_type_name(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  type_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.Param.type_name)
}
inline std::string* Param::_internal_mutable_type_name() {
  _has_bits_[0] |= 0x00000002u;
  return type_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Param::release_type_name() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.Param.type_name)
  if (!_internal_has_type_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return type_name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Param::set_allocated_type_name(std::string* type_name) {
  if (type_name != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  type_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), type_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.Param.type_name)
}

// bool bool_value = 4;
inline bool Param::_internal_has_bool_value() const {
  return oneof_value_case() == kBoolValue;
}
inline bool Param::has_bool_value() const {
  return _internal_has_bool_value();
}
inline void Param::set_has_bool_value() {
  _oneof_case_[0] = kBoolValue;
}
inline void Param::clear_bool_value() {
  if (_internal_has_bool_value()) {
    oneof_value_.bool_value_ = false;
    clear_has_oneof_value();
  }
}
inline bool Param::_internal_bool_value() const {
  if (_internal_has_bool_value()) {
    return oneof_value_.bool_value_;
  }
  return false;
}
inline void Param::_internal_set_bool_value(bool value) {
  if (!_internal_has_bool_value()) {
    clear_oneof_value();
    set_has_bool_value();
  }
  oneof_value_.bool_value_ = value;
}
inline bool Param::bool_value() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Param.bool_value)
  return _internal_bool_value();
}
inline void Param::set_bool_value(bool value) {
  _internal_set_bool_value(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.bool_value)
}

// int64 int_value = 5;
inline bool Param::_internal_has_int_value() const {
  return oneof_value_case() == kIntValue;
}
inline bool Param::has_int_value() const {
  return _internal_has_int_value();
}
inline void Param::set_has_int_value() {
  _oneof_case_[0] = kIntValue;
}
inline void Param::clear_int_value() {
  if (_internal_has_int_value()) {
    oneof_value_.int_value_ = PROTOBUF_LONGLONG(0);
    clear_has_oneof_value();
  }
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Param::_internal_int_value() const {
  if (_internal_has_int_value()) {
    return oneof_value_.int_value_;
  }
  return PROTOBUF_LONGLONG(0);
}
inline void Param::_internal_set_int_value(::PROTOBUF_NAMESPACE_ID::int64 value) {
  if (!_internal_has_int_value()) {
    clear_oneof_value();
    set_has_int_value();
  }
  oneof_value_.int_value_ = value;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Param::int_value() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Param.int_value)
  return _internal_int_value();
}
inline void Param::set_int_value(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_int_value(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.int_value)
}

// double double_value = 6;
inline bool Param::_internal_has_double_value() const {
  return oneof_value_case() == kDoubleValue;
}
inline bool Param::has_double_value() const {
  return _internal_has_double_value();
}
inline void Param::set_has_double_value() {
  _oneof_case_[0] = kDoubleValue;
}
inline void Param::clear_double_value() {
  if (_internal_has_double_value()) {
    oneof_value_.double_value_ = 0;
    clear_has_oneof_value();
  }
}
inline double Param::_internal_double_value() const {
  if (_internal_has_double_value()) {
    return oneof_value_.double_value_;
  }
  return 0;
}
inline void Param::_internal_set_double_value(double value) {
  if (!_internal_has_double_value()) {
    clear_oneof_value();
    set_has_double_value();
  }
  oneof_value_.double_value_ = value;
}
inline double Param::double_value() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Param.double_value)
  return _internal_double_value();
}
inline void Param::set_double_value(double value) {
  _internal_set_double_value(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.double_value)
}

// string string_value = 7;
inline bool Param::_internal_has_string_value() const {
  return oneof_value_case() == kStringValue;
}
inline bool Param::has_string_value() const {
  return _internal_has_string_value();
}
inline void Param::set_has_string_value() {
  _oneof_case_[0] = kStringValue;
}
inline void Param::clear_string_value() {
  if (_internal_has_string_value()) {
    oneof_value_.string_value_.Destroy(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
    clear_has_oneof_value();
  }
}
inline const std::string& Param::string_value() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Param.string_value)
  return _internal_string_value();
}
inline void Param::set_string_value(const std::string& value) {
  _internal_set_string_value(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.string_value)
}
inline std::string* Param::mutable_string_value() {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.Param.string_value)
  return _internal_mutable_string_value();
}
inline const std::string& Param::_internal_string_value() const {
  if (_internal_has_string_value()) {
    return oneof_value_.string_value_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void Param::_internal_set_string_value(const std::string& value) {
  if (!_internal_has_string_value()) {
    clear_oneof_value();
    set_has_string_value();
    oneof_value_.string_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  oneof_value_.string_value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Param::set_string_value(std::string&& value) {
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.string_value)
  if (!_internal_has_string_value()) {
    clear_oneof_value();
    set_has_string_value();
    oneof_value_.string_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  oneof_value_.string_value_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.Param.string_value)
}
inline void Param::set_string_value(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  if (!_internal_has_string_value()) {
    clear_oneof_value();
    set_has_string_value();
    oneof_value_.string_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  oneof_value_.string_value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{},
      ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.Param.string_value)
}
inline void Param::set_string_value(const char* value,
                             size_t size) {
  if (!_internal_has_string_value()) {
    clear_oneof_value();
    set_has_string_value();
    oneof_value_.string_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  oneof_value_.string_value_.Set(
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size),
      GetArena());
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.Param.string_value)
}
inline std::string* Param::_internal_mutable_string_value() {
  if (!_internal_has_string_value()) {
    clear_oneof_value();
    set_has_string_value();
    oneof_value_.string_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  return oneof_value_.string_value_.Mutable(
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Param::release_string_value() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.Param.string_value)
  if (_internal_has_string_value()) {
    clear_has_oneof_value();
    return oneof_value_.string_value_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  } else {
    return nullptr;
  }
}
inline void Param::set_allocated_string_value(std::string* string_value) {
  if (has_oneof_value()) {
    clear_oneof_value();
  }
  if (string_value != nullptr) {
    set_has_string_value();
    oneof_value_.string_value_.UnsafeSetDefault(string_value);
    ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena();
    if (arena != nullptr) {
      arena->Own(string_value);
    }
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.Param.string_value)
}

// optional bytes proto_desc = 8;
inline bool Param::_internal_has_proto_desc() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Param::has_proto_desc() const {
  return _internal_has_proto_desc();
}
inline void Param::clear_proto_desc() {
  proto_desc_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Param::proto_desc() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Param.proto_desc)
  return _internal_proto_desc();
}
inline void Param::set_proto_desc(const std::string& value) {
  _internal_set_proto_desc(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.proto_desc)
}
inline std::string* Param::mutable_proto_desc() {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.Param.proto_desc)
  return _internal_mutable_proto_desc();
}
inline const std::string& Param::_internal_proto_desc() const {
  return proto_desc_.Get();
}
inline void Param::_internal_set_proto_desc(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  proto_desc_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Param::set_proto_desc(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  proto_desc_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.Param.proto_desc)
}
inline void Param::set_proto_desc(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  proto_desc_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.Param.proto_desc)
}
inline void Param::set_proto_desc(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000004u;
  proto_desc_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.Param.proto_desc)
}
inline std::string* Param::_internal_mutable_proto_desc() {
  _has_bits_[0] |= 0x00000004u;
  return proto_desc_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Param::release_proto_desc() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.Param.proto_desc)
  if (!_internal_has_proto_desc()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return proto_desc_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Param::set_allocated_proto_desc(std::string* proto_desc) {
  if (proto_desc != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  proto_desc_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), proto_desc,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.Param.proto_desc)
}

inline bool Param::has_oneof_value() const {
  return oneof_value_case() != ONEOF_VALUE_NOT_SET;
}
inline void Param::clear_has_oneof_value() {
  _oneof_case_[0] = ONEOF_VALUE_NOT_SET;
}
inline Param::OneofValueCase Param::oneof_value_case() const {
  return Param::OneofValueCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// NodeName

// optional string value = 1;
inline bool NodeName::_internal_has_value() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool NodeName::has_value() const {
  return _internal_has_value();
}
inline void NodeName::clear_value() {
  value_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& NodeName::value() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.NodeName.value)
  return _internal_value();
}
inline void NodeName::set_value(const std::string& value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.NodeName.value)
}
inline std::string* NodeName::mutable_value() {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.NodeName.value)
  return _internal_mutable_value();
}
inline const std::string& NodeName::_internal_value() const {
  return value_.Get();
}
inline void NodeName::_internal_set_value(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void NodeName::set_value(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  value_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.NodeName.value)
}
inline void NodeName::set_value(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.NodeName.value)
}
inline void NodeName::set_value(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.NodeName.value)
}
inline std::string* NodeName::_internal_mutable_value() {
  _has_bits_[0] |= 0x00000001u;
  return value_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* NodeName::release_value() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.NodeName.value)
  if (!_internal_has_value()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return value_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void NodeName::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  value_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.NodeName.value)
}

// -------------------------------------------------------------------

// ParamName

// optional string value = 1;
inline bool ParamName::_internal_has_value() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ParamName::has_value() const {
  return _internal_has_value();
}
inline void ParamName::clear_value() {
  value_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ParamName::value() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ParamName.value)
  return _internal_value();
}
inline void ParamName::set_value(const std::string& value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.ParamName.value)
}
inline std::string* ParamName::mutable_value() {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ParamName.value)
  return _internal_mutable_value();
}
inline const std::string& ParamName::_internal_value() const {
  return value_.Get();
}
inline void ParamName::_internal_set_value(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ParamName::set_value(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  value_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.ParamName.value)
}
inline void ParamName::set_value(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.ParamName.value)
}
inline void ParamName::set_value(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.ParamName.value)
}
inline std::string* ParamName::_internal_mutable_value() {
  _has_bits_[0] |= 0x00000001u;
  return value_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ParamName::release_value() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.ParamName.value)
  if (!_internal_has_value()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return value_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ParamName::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  value_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.ParamName.value)
}

// -------------------------------------------------------------------

// BoolResult

// optional bool value = 1;
inline bool BoolResult::_internal_has_value() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool BoolResult::has_value() const {
  return _internal_has_value();
}
inline void BoolResult::clear_value() {
  value_ = false;
  _has_bits_[0] &= ~0x00000001u;
}
inline bool BoolResult::_internal_value() const {
  return value_;
}
inline bool BoolResult::value() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.BoolResult.value)
  return _internal_value();
}
inline void BoolResult::_internal_set_value(bool value) {
  _has_bits_[0] |= 0x00000001u;
  value_ = value;
}
inline void BoolResult::set_value(bool value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.BoolResult.value)
}

// -------------------------------------------------------------------

// Params

// repeated .apollo.cyber.proto.Param param = 1;
inline int Params::_internal_param_size() const {
  return param_.size();
}
inline int Params::param_size() const {
  return _internal_param_size();
}
inline void Params::clear_param() {
  param_.Clear();
}
inline ::apollo::cyber::proto::Param* Params::mutable_param(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.Params.param)
  return param_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::Param >*
Params::mutable_param() {
  // @@protoc_insertion_point(field_mutable_list:apollo.cyber.proto.Params.param)
  return &param_;
}
inline const ::apollo::cyber::proto::Param& Params::_internal_param(int index) const {
  return param_.Get(index);
}
inline const ::apollo::cyber::proto::Param& Params::param(int index) const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Params.param)
  return _internal_param(index);
}
inline ::apollo::cyber::proto::Param* Params::_internal_add_param() {
  return param_.Add();
}
inline ::apollo::cyber::proto::Param* Params::add_param() {
  // @@protoc_insertion_point(field_add:apollo.cyber.proto.Params.param)
  return _internal_add_param();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::cyber::proto::Param >&
Params::param() const {
  // @@protoc_insertion_point(field_list:apollo.cyber.proto.Params.param)
  return param_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace cyber
}  // namespace apollo

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::apollo::cyber::proto::ParamType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::cyber::proto::ParamType>() {
  return ::apollo::cyber::proto::ParamType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_cyber_2fproto_2fparameter_2eproto
