name: ubuntu20.04 v10.0.0 build x86-64
run-name: ubuntu20 x86-64

on:
  push:
    branches:
      - v10.0.0

jobs:
  build-amd-ubuntu20:
    runs-on: ubuntu-latest
    container:
      image: docker://ubuntu:20.04
      options: --volume ${{ github.workspace }}:/workspace/${{ github.repository }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update
          apt install -y sudo lsb-release git wget libcurl4-openssl-dev pkg-config g++ cmake uuid-dev libncurses5-dev python3-dev autoconf automake libtool libeigen3-dev libtiff-dev libsqlite3-dev sqlite3
          cd /workspace/${{ github.repository }} && python3 install.py

      - name: Build
        run: |
          echo "-----------------------"
          uname -a
          lsb_release -a
          echo "-----------------------"
          bash -c "cd /workspace/${{ github.repository }} && source install/setup.bash && mkdir -p build && cd build && cmake .. && make -j$(nproc)"
