name: ubuntu18.04 v10.0.0 build x86-64
run-name: ubuntu18 x86-64

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

on:
  push:
    branches:
      - v10.0.0

  pull_request:
    branches:
      - v10.0.0

jobs:
  build-amd-ubuntu18:
    runs-on: ubuntu-latest
    container:
      image: docker://ubuntu:18.04
      # options: --volume ${{ github.workspace }}:/workspace/${{ github.repository }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v1 # https://github.com/actions/checkout/issues/1590
        with:
          fetch-depth: 1

      - name: Install
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update
          apt install -y sudo lsb-release git wget libcurl4-openssl-dev pkg-config g++ cmake uuid-dev libncurses5-dev python3-dev autoconf automake libtool libeigen3-dev libtiff-dev libsqlite3-dev sqlite3
          python3 install.py

      - name: Build
        run: |
          echo "-----------------------"
          uname -a
          lsb_release -a
          echo "-----------------------"
          bash -c "source install/setup.bash && mkdir -p build && cd build && cmake .. && make -j$(nproc)"
